{% set name = "bpytop" %}
{% set version = "1.0.67" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bpytop-{{ version }}.tar.gz
  sha256: 8b338e3627fa6e991e836bee61ef38988f6a7a3a37dc05c757a92ba4378f95bb

build:
  number: 0
  noarch: python
  entry_points:
    - bpytop = bpytop:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - poetry >=0.12
  run:
    - psutil >=5.7.0,<6.0.0
    - python >=3.6
    # Require the unix virtual package as a runtime dep
    - __unix

test:
  imports:
    - bpytop
  commands:
    - pip check
    - bpytop --help
  requires:
    - pip

about:
  home: https://github.com/aristocratos/bpytop
  summary: Resource monitor that shows usage and stats for processor, memory, disks, network and processes.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ickc
